name: Publish on GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - source/**
      - samplecode/**
      - .github/workflows/publish-pages.yml
      - requirements.in

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - id: sitepackages
        run: echo "path=$(python -c 'import site; print(site.getsitepackages()[0])')" >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.in
      - name: Arrange Reveal.js assets
        uses: ftnext/action-fetch-revealjs@main
        with:
          version: 4.2.1
          dest_dir: ${{ steps.sitepackages.outputs.path }}/sphinx_revealjs/themes/sphinx_revealjs/static/revealjs4
      - name: Build slide
        run: |
          make revealjs
          rm -r build/revealjs/_sources
      - name: Publish on GitHub Pages
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: build/revealjs
          github_token: ${{ secrets.GITHUB_TOKEN }}
